### ISSUE TITLE
Error while running on node v0.10.28

### ISSUE THREAD

**Issue by nukulb** [achingbrain/pm2-web#32]
After starting the pm2-web and refreshing the page I get the following error

```
2014-10-16T02:39:52.320Z - error: PM2 Uncaught exception TypeError: Cannot read property 'pm_id' of undefined
    at WebSocketResponder._broadcastLog (/usr/local/lib/node_modules/pm2-web/server/components/WebSocketResponder.js:109:57)
    at WildEmitter.emit (/usr/local/lib/node_modules/pm2-web/node_modules/wildemitter/wildemitter.js:104:30)
    at null.<anonymous> (/usr/local/lib/node_modules/pm2-web/server/components/PM2Listener.js:107:8)
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2-web/node_modules/pm2-interface/node_modules/pm2-axon/lib/sockets/sub-emitter.js:52:19)
    at Parser.EventEmitter.emit (events.js:95:17)
    at Parser._write (/usr/local/lib/node_modules/pm2-web/node_modules/pm2-interface/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Parser.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:582:24)

/usr/local/lib/node_modules/pm2-web/server/app.js:65
        throw exception;
              ^
TypeError: Cannot read property 'pm_id' of undefined
    at WebSocketResponder._broadcastLog (/usr/local/lib/node_modules/pm2-web/server/components/WebSocketResponder.js:109:57)
    at WildEmitter.emit (/usr/local/lib/node_modules/pm2-web/node_modules/wildemitter/wildemitter.js:104:30)
    at null.<anonymous> (/usr/local/lib/node_modules/pm2-web/server/components/PM2Listener.js:107:8)
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2-web/node_modules/pm2-interface/node_modules/pm2-axon/lib/sockets/sub-emitter.js:52:19)
    at Parser.EventEmitter.emit (events.js:95:17)
    at Parser._write (/usr/local/lib/node_modules/pm2-web/node_modules/pm2-interface/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Parser.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:582:24)
```

**Comment by zxqfox** [comment]
Guys, did you notice that pm2-interface is deprecated: https://github.com/unitech/pm2-interface ?

**Comment by achingbrain** [comment]
Yes.  Sadly they haven't really offered much of an alternative for connecting to pm2 managed processes running on a remote machine in a secure way - it kills the monitoring-multiple-remote-machines aspect of pm2-web which is kind of why I wrote it in the first place.

Most of my energy is going into [boss](https://www.npmjs.com/package/process-boss) at the moment, it's got a neat web interface that's a lot better than pm2-web - you should check it out.

**Comment by zxqfox** [comment]
@achingbrain I'm not sure how it worked earlier (in 0.9, 0.10, 0.11) but for now `pm2 god daemon` created for EACH user and should be handled separately. So for now: one machine → many users, one user → many processes. It looks like there should be an pm2-agent on each machine who could access `pm2 god daemon` of each user (so it should be started by root).

Do you want to support pm2 in boss? For now I'm strongly looking for a process manager for several dev servers and can help with development and bug fixing. If you mind.

**Comment by achingbrain** [comment]
Yep, the solution for multi-user pm2 is that you're supposed to run a separate pm2 daemon for each user.  This doesn't seem terribly efficient.

What do you mean by 'support pm2 in boss'?  Do you mean monitor pm2 daemons with boss' web interface?
