### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by adros** [achingbrain/pm2-web#43]
PM2 now runs also on windows, but it is not possible to install pm2-web on this platform. The problem is dependency on  'pwuid' module, which is not supported in win.

**Comment by dlinx** [comment]
Please add support for windows also

**Comment by mindej** [comment]
+1

**Comment by AnatoliyAksenov** [comment]
+1
<pre>
2935 verbose stack Error: Unsupported platform for pwuid@1.1.1: wanted {"name":"pwuid","version":"1.1.1","description":"getpwuid() binding - returns username, name, home directory, shell, gid from uid","keywords":["binding","native","addon","uid","gid","pw","getpwuid","posix","unix","shell","home","dir","username"],"license":"MIT","author":{"name":"Sindre Sorhus","email":"sindresorhus@gmail.com","url":"sindresorhus.com"},"files":["index.js","binding.gyp","binding.cc"],"repository":{"type":"git","url":"git+https://github.com/sindresorhus/pwuid.git"},"scripts":{"test":"xo && ava","install":"node-gyp rebuild"},"dependencies":{"bindings":"^1.2.1","nan":"^2.1.0"},"devDependencies":{"ava":"*","xo":"*"},"engines":{"node":">=0.10.0"},"os":["!win32"],"gypfile":true,"bugs":{"url":"https://github.com/sindresorhus/pwuid/issues"},"homepage":"https://github.com/sindresorhus/pwuid#readme","_id":"pwuid@1.1.1","bundleDependencies":false,"deprecated":false,"_resolved":"https://registry.npmjs.org/pwuid/-/pwuid-1.1.1.tgz","_integrity":"sha1-NdDojtVPK9aS9Zm44M3uNg0n+1A=","_shasum":"35d0e88ed54f2bd692f599b8e0cdee360d27fb50","_from":"pwuid@^1.0","_requested":{"type":"range","registry":true,"raw":"pwuid@^1.0","name":"pwuid","escapedName":"pwuid","rawSpec":"^1.0","saveSpec":null,"fetchSpec":"^1.0"},"_spec":"pwuid@^1.0","_where":"C:\\Users\\aksenov_aa\\AppData\\Roaming\\npm\\node_modules\\pm2-web"} (current: {"os":"win32","cpu":"x64"})
2935 verbose stack     at checkPlatform (C:\Users\aksenov_aa\AppData\Roaming\npm\node_modules\npm\node_modules\npm-install-checks\index.js:45:14)
2935 verbose stack     at tryCatcher (C:\Users\aksenov_aa\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
2935 verbose stack     at ret (eval at makeNodePromisifiedEval (C:\Users\aksenov_aa\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promisify.js:1:1), <anonymous>:13:39)
2935 verbose stack     at readJson.then.catch.then (C:\Users\aksenov_aa\AppData\Roaming\npm\node_modules\npm\lib\install\action\refresh-package-json.js:31:12)
2935 verbose stack     at tryCatcher (C:\Users\aksenov_aa\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
2935 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\aksenov_aa\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
2935 verbose stack     at Promise._settlePromise (C:\Users\aksenov_aa\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
2935 verbose stack     at Promise._settlePromise0 (C:\Users\aksenov_aa\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
2935 verbose stack     at Promise._settlePromises (C:\Users\aksenov_aa\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
2935 verbose stack     at Promise._fulfill (C:\Users\aksenov_aa\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:638:18)
2935 verbose stack     at Promise._settlePromise (C:\Users\aksenov_aa\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:582:21)
2935 verbose stack     at Promise._settlePromise0 (C:\Users\aksenov_aa\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
2935 verbose stack     at Promise._settlePromises (C:\Users\aksenov_aa\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
2935 verbose stack     at Promise._fulfill (C:\Users\aksenov_aa\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:638:18)
2935 verbose stack     at Promise._resolveCallback (C:\Users\aksenov_aa\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:432:57)
2935 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\aksenov_aa\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:524:17)
2936 verbose pkgid pwuid@1.1.1
2937 verbose cwd C:\pm2-webshell
2938 verbose Windows_NT 6.1.7601
2939 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aksenov_aa\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "pm2-web" "-g"
2940 verbose node v7.6.0
2941 verbose npm  v5.3.0
2942 error code EBADPLATFORM
2943 error notsup Unsupported platform for pwuid@1.1.1: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
2944 error notsup Valid OS:    !win32
2944 error notsup Valid Arch:  any
2944 error notsup Actual OS:   win32
2944 error notsup Actual Arch: x64
2945 verbose exit [ 1, true ]
</pre>

**Comment by jfbvm** [comment]
+1

**Comment by BugKun** [comment]
+1

**Comment by donaldr** [comment]
+1

**Comment by onesmail** [comment]
+1
