### ISSUE TITLE
Error when upgrading io.js

### ISSUE THREAD

**Issue by ChrisPearce** [achingbrain/pm2-web#47]
When running pm2-web under io.js (v1.7.1) I am encountering the following error:

/usr/local/lib/node_modules/pm2-web/node_modules/pwuid/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module version mismatch. Expected 43, got 14.
    at Error (native)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at bindings (/usr/local/lib/node_modules/pm2-web/node_modules/pwuid/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2-web/node_modules/pwuid/index.js:2:34)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)

This appears to be related to the pwuid dependency.

**Comment by ChrisPearce** [comment]
Solved by rebuilding using npm.
