### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by wormen** [achingbrain/pm2-web#53]
```
../src/dns_sd.cpp:90: error: ‘InvocationCallback’ was not declared in this scope
../src/dns_sd.cpp:95: error: expected constructor, destructor, or type conversion before ‘<’ token
../src/dns_sd.cpp:321: error: expected ‘}’ at end of input
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory `/root/.nvm/versions/io.js/v3.2.0/lib/node_modules/pm2-web/node_modules/mdns2/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/io.js/v3.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.12.2.el6.x86_64
gyp ERR! command "/root/.nvm/versions/io.js/v3.2.0/bin/iojs" "/root/.nvm/versions/io.js/v3.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.nvm/versions/io.js/v3.2.0/lib/node_modules/pm2-web/node_modules/mdns2
gyp ERR! node -v v3.2.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"3.2.0","npm":"2.13.3"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"3.2.0","npm":"2.13.3"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"3.2.0","npm":"2.13.3"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"3.2.0","npm":"2.13.3"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"3.2.0","npm":"2.13.3"})

> ws@0.4.32 install /root/.nvm/versions/io.js/v3.2.0/lib/node_modules/pm2-web/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/root/.nvm/versions/io.js/v3.2.0/lib/node_modules/pm2-web/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/root/.nvm/versions/io.js/v3.2.0/lib/node_modules/pm2-web/node_modules/ws/build'
npm WARN optional dep failed, continuing mdns2@2.1.4
npm ERR! Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! argv "/root/.nvm/versions/io.js/v3.2.0/bin/iojs" "/root/.nvm/versions/io.js/v3.2.0/bin/npm" "install" "-g" "pm2-web"
npm ERR! node v3.2.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pwuid@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pwuid@1.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pwuid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pwuid
npm ERR! There is likely additional logging output above.

```

The most interesting line 3
I use iojs 0.3.2

**Comment by minzhitang** [comment]
I met the same problem

**Comment by Paolocargnin** [comment]
+1 Ubuntu 14.04

**Comment by rambo-panda** [comment]
+1 CentOS release 6.5 (Final)

**Comment by constantinbeleca** [comment]
+1 Ubuntu 14.04LTS

**Comment by hchfly** [comment]
+1 Ubuntu 14.04LTS

**Comment by yuhongshuai** [comment]
**+1 centos7.5**

`[root@instance-n1 ~ 01:58:14]#npm install -g pm2-web
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated hawk@0.10.2: This version has been deprecated. Please upgrade to the latest version to get the best features, bug fixes, and security patches.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated boom@0.3.8: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@0.1.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@0.7.6: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@0.1.4: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
/usr/local/bin/pm2-web -> /usr/local/lib/node_modules/pm2-web/bin/pm2-web.sh

> mdns2@2.1.4 install /usr/local/lib/node_modules/pm2-web/node_modules/mdns2
> node-gyp rebuild

gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 3.10.0-957.1.3.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/pm2-web/node_modules/mdns2
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> pwuid@1.1.1 install /usr/local/lib/node_modules/pm2-web/node_modules/pwuid
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/12.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/pm2-web/node_modules/pwuid/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/pm2-web/node_modules/pwuid/.node-gyp'
gyp ERR! System Linux 3.10.0-957.1.3.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/pm2-web/node_modules/pwuid
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mdns2@2.1.4 (node_modules/pm2-web/node_modules/mdns2):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mdns2@2.1.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pwuid@1.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pwuid@1.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-26T06_02_18_842Z-debug.log
`

**Comment by HighNetFather** [comment]
+1 macos (catalina)

**Comment by 82kg** [comment]
+1 centos7

**Comment by frankfoxy** [comment]
+1 centos7.8

**Comment by gaozhengxin** [comment]
+1 iphone13 pro max
