### ISSUE TITLE
Node v7: Could not locate the bindings file

### ISSUE THREAD

**Issue by 94cstyles** [achingbrain/pm2-web#58]
```
/usr/local/lib/node_modules/pm2-web/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/build/binding.node
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/build/Debug/binding.node
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/build/Release/binding.node
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/out/Debug/binding.node
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/Debug/binding.node
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/out/Release/binding.node
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/Release/binding.node
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/build/default/binding.node
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/compiled/7.5.0/darwin/x64/binding.node
    at bindings (/usr/local/lib/node_modules/pm2-web/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2-web/node_modules/pwuid/index.js:2:34)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2-web/server/components/Configuration.js:5:10)
```

**Comment by yale8848** [comment]
node v7.6.0 also meet this problem

**Comment by zanderisrael** [comment]
Same Here

**Comment by yesoreyeram** [comment]
With node v8 also this issue happening

**Comment by DenisLaboureyras** [comment]
build pm2-web with unsafe permissions did the trick for me : 
`sudo npm install -g pm2-web --unsafe-perm`

**Comment by jackyon** [comment]
+1, any solution?

**Comment by y4nnick** [comment]
+1 --unsafe-perm doesn't resolve this for me.
I am on node v9.11.1 .

**Comment by vuthaihoc** [comment]
I cd to folder `cd /usr/lib/node_modules/pm2-web/node_modules/pwuid/` and then rebuild with this command `sudo node-gyp rebuild`
